namespace HackTheTrackAnalytics.Models;

/// <summary>
/// Pit strategy recommendation generated by the AI engine
/// </summary>
public record PitRecommendation
{
    public int RecommendedLap { get; init; }
    public int CurrentLap { get; init; }
    public int LapsUntilPit => Math.Max(0, RecommendedLap - CurrentLap);
    public string Reason { get; init; } = string.Empty;
    public TimeSpan ExpectedTimeGain { get; init; }
    public double TireWearPercent { get; init; }
    public PitUrgency Urgency { get; init; }
    public bool IsCautionOpportunity { get; init; }
    public string Strategy { get; init; } = string.Empty;

    // Additional context
    public TimeSpan CurrentLapTimeDelta { get; init; }  // vs. best lap
    public double AverageBrakePressure { get; init; }
    public double TrackTemperature { get; init; }
    public List<string> Factors { get; init; } = new();

    public string GetDisplayMessage()
    {
        if (LapsUntilPit == 0)
            return $"🏁 PIT THIS LAP! {Reason}";
        if (LapsUntilPit == 1)
            return $"⚠️ PIT NEXT LAP ({Reason})";

        return $"📊 Optimal pit in {LapsUntilPit} laps ({Reason})";
    }
}

public enum PitUrgency
{
    Info,        // Just FYI
    Advisory,    // Should consider
    Warning,     // Should pit soon
    Critical     // Pit now!
}

/// <summary>
/// Tire degradation model
/// </summary>
public record TireDegradation
{
    public int CurrentLap { get; init; }
    public double WearPercent { get; init; }
    public TimeSpan LapTimeDelta { get; init; }
    public double AverageBrakePressure { get; init; }
    public double PeakBrakePressure { get; init; }
    public double TemperatureEffect { get; init; }
    public bool IsOnBestLapPace => LapTimeDelta.TotalSeconds < 1.0;
    public bool NeedsPitSoon => WearPercent > 75 || LapTimeDelta.TotalSeconds > 1.5;

    public static TireDegradation Calculate(
        int currentLap,
        List<LapData> laps,
        List<TelemetryRecord> telemetry,
        BestLapBenchmark benchmark,
        double trackTemp)
    {
        if (!laps.Any())
            return new TireDegradation { CurrentLap = currentLap };

        // Get recent laps (last 5)
        var recentLaps = laps.TakeLast(5).ToList();

        // Calculate lap time degradation
        var avgRecentTime = TimeSpan.FromSeconds(recentLaps.Average(l => l.LapTime.TotalSeconds));
        var delta = avgRecentTime - benchmark.BestLapTime;

        // Estimate wear from lap count and lap time delta
        var baseLapWear = (currentLap / 30.0) * 100.0;  // Assume 30 lap stint
        var deltaWear = (delta.TotalSeconds / 3.0) * 100.0;  // 3s delta = 100% wear

        // Temperature effect
        var tempMultiplier = trackTemp switch
        {
            < 25 => 0.9,
            < 35 => 1.0,
            < 45 => 1.3,
            _ => 1.5
        };

        var totalWear = Math.Min(100, (baseLapWear + deltaWear) * tempMultiplier);

        // Brake pressure analysis (higher = more tire stress)
        var avgBrake = telemetry
            .Where(t => t.Lap == currentLap && t.BrakeFront.HasValue)
            .Select(t => t.BrakeFront!.Value)
            .DefaultIfEmpty(0)
            .Average();

        var peakBrake = telemetry
            .Where(t => t.Lap == currentLap && t.BrakeFront.HasValue)
            .Select(t => t.BrakeFront!.Value)
            .DefaultIfEmpty(0)
            .Max();

        return new TireDegradation
        {
            CurrentLap = currentLap,
            WearPercent = totalWear,
            LapTimeDelta = delta,
            AverageBrakePressure = avgBrake,
            PeakBrakePressure = peakBrake,
            TemperatureEffect = tempMultiplier
        };
    }
}
